---
title: "HW4"
output: html_document
---
```{r, include=FALSE}
library(tidyverse)
library(rsample)
```

# 1. Question 5 Data Cleaning
```{r}
dat <- read.csv("Data/Default.csv")

glimpse(dat)
tail(dat)
slice_sample(dat,n = 10)

# hot swap 'Yes' and 'No' in default in student columns to 1 and 0
dat <- dat |>
  mutate(
    default = if_else(default == "Yes", 1, 0),
    student = if_else(student == "Yes", 1, 0)
  )
```

## Q.5.A
```{r}
# fit a logistic a regression model to the training data
modelA <- glm(default ~ income + balance, family = "binomial", data = dat)
summary(modelA)
```

## Q.5.B
```{r, results='hide'}
# The validation set approach
set.seed(1)

# naively split the data into training and test sets
obs <- dat |> nrow()
train <- sample(obs, 0.8*obs)

# fit a logistic a regression model to the training data
modelB1 <- glm(default ~ income + balance, family = "binomial", data = dat, subset = train)
summary(modelB1)

# calculate the MSE
# MSE1 <- mean((dat$default = predict(modelB1, dat))[-train]^2)
```

```{r, results='hide'}
# The validation set approach
set.seed(2)

# naively split the data into training and test sets
obs <- dat |> nrow()
train <- sample(obs, 0.8*obs)

# fit a logistic a regression model to the training data
modelB2 <- glm(default ~ income + balance, family = "binomial", data = dat, subset = train)
summary(modelB2)

# calculate the MSE

```

```{r, results='hide'}
# The validation set approach
set.seed(3)

# naively split the data into training and test sets
obs <- dat |> nrow()
train <- sample(obs, 0.8*obs)

# fit a logistic a regression model to the training data
modelB3 <- glm(default ~ income + balance, family = "binomial", data = dat, subset = train)
summary(modelB3)

# calculate the MSE

```

# 2. Question 10 in Section 6.6

# 3. Question 11 in Section 6.6



